---
title: "rat-hex"
format: html
---


 ## Example from FMG
[FMG-hex](https://github.com/ForestManagementGeodatabase/FMG-hex)

```{r}
library(hexSticker)
library(magick)
```

```{r}
library(showtext)
## Loading Google fonts (http://www.google.com/fonts)
sysfonts::font_add_google(name = "Just Another Hand", family = "Just Another Hand")
## Automatically use showtext to render text for future devices
showtext::showtext_auto()

```

```{r}

fc_rat_hex_image <- "images/pexels-asil-18985377.png"

filename <- "FG_hexes/fc_rat_hex.png"

fg <- sticker(subplot = fc_rat_hex_image, 
               s_x = 1,
               s_y = 1,
               s_width = 1.4,
               package = "Floodplain\nConnectivity\nRAT",
               p_x = 1,
               p_y = 1.47,
               lineheight =0.23,
               p_color = "cornsilk",
               
               p_family = "Just Another Hand",
               p_size = 19,
               h_size = 3,
               h_color = "darkolivegreen",
               white_around_sticker = TRUE,
               filename = filename)

fuzz <- 30
p <- image_read(filename)
pp <- p %>%
  image_fill(color = "transparent", refcolor = "white", fuzz = fuzz, point = "+1+1") %>%
  image_fill(color = "transparent", refcolor = "white", fuzz = fuzz, point = paste0("+", image_info(p)$width-1, "+1")) %>%
  image_fill(color = "transparent", refcolor = "white", fuzz = fuzz, point = paste0("+1", "+", image_info(p)$height-1)) %>%
  image_fill(color = "transparent", refcolor = "white", fuzz = fuzz, point = paste0("+", image_info(p)$width-1, "+", image_info(p)$height-1))
image_write(image = pp, path = "FG_hexes/fc_rat_hex_image.png")
file.show("fc_rat_hex_image.png")

```